apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "quality-gate"
      sequences:
        - name: "performance"
          tasks:
            - name: "test"
            - name: "evaluation"
